sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: test
      install:
        - npm ci
      script:
        - npm run test:single
        - npm run build
    - stage: release
      if: branch = master
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release