sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 'lts/*'
install:
  - npm ci
script:
  - npm run test:single
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"