sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'lts/*'
before_install:
  - npm i -g npm@^6.4.1
before_script:
  - npm ci
script:
  - npm run test:single
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
